controller_list:
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - left_shoulder2_mount_joint
      - left_shoulder2_joint
      - left_upper_arm_joint
      - left_elbow_joint
      - left_forearm_joint
      - left_wrist_joint
      - left_handunit_mount_joint
  - name: fake_left_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - left_handunit_mount_joint
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - right_shoulder2_mount_joint
      - right_shoulder2_joint
      - right_upper_arm_joint
      - right_elbow_joint
      - right_forearm_joint
      - right_wrist_joint
      - right_handunit_mount_joint
  - name: fake_right_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - right_handunit_mount_joint
initial:  # Define initial robot poses per group
  - group: left_arm
    pose: left_home
  - group: right_arm
    pose: right_home