left_arm_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    []
  gains:
    {}
right_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    []
  gains:
    {}