metalimbs:

    left_shoulder2_mount_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: left_shoulder2_mount_joint

    right_shoulder2_mount_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: right_shoulder2_mount_joint

    left_shoulder2_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: left_shoulder2_joint

    right_shoulder2_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: right_shoulder2_joint

    left_upper_arm_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: left_upper_arm_joint

    right_upper_arm_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: right_upper_arm_joint

    left_elbow_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: left_elbow_joint

    right_elbow_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: right_elbow_joint

    left_forearm_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: left_forearm_joint

    right_forearm_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: right_forearm_joint

    left_wrist_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: left_wrist_joint

    right_wrist_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: right_wrist_joint

    left_handunit_mount_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: left_handunit_mount_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}

    right_handunit_mount_joint_position_controller:
        type: position_controllers/JointPositionController
        joint: right_handunit_mount_joint
        pid: {p: 100.0, i: 0.01, d: 10.0}
