controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

arm_controller:
  ros__parameters:
    joints:
      - left_shoulder2_mount_joint
      - left_shoulder2_joint
      - left_upper_arm_joint
      - left_elbow_joint
      - left_forearm_joint
      - left_wrist_joint
      - left_handunit_mount_joint
      - right_shoulder2_mount_joint
      - right_shoulder2_joint
      - right_upper_arm_joint
      - right_elbow_joint
      - right_forearm_joint
      - right_wrist_joint
      - right_handunit_mount_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.01
      goal_time: 5.0