[tool.pysen]
version = "0.10"

[tool.pysen.plugin.clang_format]
function = "pysen_plugins::clang_format"

[tool.pysen.lint]
enable_black = false
enable_flake8 = false
enable_isort = false
enable_mypy = false
mypy_preset = "strict"
line_length = 88
py_version = "py38"

[tool.pysen.lint.source]
  includes = ["."]
